apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stored-value-on-boarding
  namespace: cnm
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: cnm
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: cnm
    releaseName: stored-value-apac-prd
    applicationName: stored-value
    gitRepo:
      repoName: stored-value-config
      ref:
        branch: apac-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/stored-value/values.yaml
        - helm/stored-value/overrides/values-apac-prod.yaml
    alert:
      channel: bsp-apac-prd-flux-applications
