apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-auditing-onboarding
  namespace: prd-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: prd-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: prd-apims
    releaseName: auditing-napac-production-napac-n0r5scy
    applicationName: auditing
    gitRepo:
      repoName: apims-auditing-config
      ref:
        branch: napac-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/auditing/values.yaml
        - helm/auditing/overrides/napac-prod.yaml
    alert:
      channel: apims-auditing-gitops
