apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd-apims
resources:
  - ../../../../../common-resources/default/certs/ncrcloud
  - ../../../../../common-resources/default/github
  - ../../../../../common-resources/default/slack
  - namespace.yaml
  - api-launch.yaml
  - entitlements.yaml
  - teams.yaml
  - bsp-security-proxy.yaml
  - analytics.yaml
  - auditing.yaml
  - simulator.yaml
  - export-data.yaml