apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: core-on-boarding
  namespace: core-namer-prd
spec:
  interval: 60m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: core-namer-prd
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: core-namer-prd
    releaseName: core
    applicationName: nep-core
    gitRepo:
      repoName: nep-core-config
      ref:
        branch: namer-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      timeout: 55m # Needed to give other jobs time to finish.
      interval: 60m
      valuesFiles:
        - helm/nep-core/values.yaml
        - helm/nep-core/overrides/namer-prd.yaml
    alert:
      channel: core-gitops
