apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: message-ingest-on-boarding
  namespace: notifications-napac-prd
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: notifications-napac-prd
      interval: 5m
## Values overridden for this deployment
  values:
    namespace: notifications-napac-prd
    releaseName: message-ingest
    applicationName: message-ingest
    gitRepo:
      repoName: core-config
      ref:
        branch: message-ingest-napac-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/message-ingest/values.yaml
        - helm/message-ingest/overrides/napac-prd.yaml
    alert:
      channel: core-gitops
