apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-launch-v2-onboarding
  namespace: rc-dev-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: rc-dev-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: rc-dev-apims
    releaseName: api-launch-v2
    applicationName: api-launch-v2
    gitRepo:
      repoName: api-launch-config
      ref:
        branch: namer-rc-dev
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp          
    helmRelease:
      timeout: 15m
      valuesFiles:
        - helm/api-launch-v2/values.yaml
        - helm/api-launch-v2/overrides/rc-dev.yaml
    alert:
      channel: api-launch-gitops
