apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identity-ncr-com-tls
  namespace: istio-system
spec:
  refreshInterval: 10m                # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: es-cluster-secret-store     # name of the SecretStore (or kind specified)
  target:
    creationPolicy: Owner
  data:
  - secretKey: tls.crt               # name of the GCPSM secret key
    remoteRef:
      key: IDENTITY_NCR_COM_CERT
  - secretKey: tls.key                # name of the GCPSM secret key.
    remoteRef:
      key: IDENTITY_NCR_COM_DECRYPTED_KEY
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
  name: gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'identity.ncr.com'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: identity-ncr-com-tls