apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: digitalcoupon
spec:
  path: ./apps/business-services-platform/EMEA/production/cnm/digitalcoupon
  sourceRef:
    kind: GitRepository
    name: bsp-sre-gitops
    namespace: cnm
  interval: 30s
  prune: false
