apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- applications-namer-sandbox
- applications-namer-dev
- users-namer-sandbox
- users-namer-dev
- journaling-namer-sandbox
- journaling-namer-dev
- core-namer-sandbox
- core-namer-dev
- messaging-health-monitor-namer-sandbox
- messaging-health-monitor-namer-dev
- notifications-namer-sandbox
- notifications-namer-dev
- site-security-namer-sandbox
- site-security-namer-dev
- dev-apims-gitops
- dev-apims
- rc-dev-apims
- ncr-id
- gateway.yaml
- github-notifier
- flagger
