apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mhm-on-boarding
  namespace: mhm-namer-stg
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: mhm-namer-stg
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: mhm-namer-stg
    releaseName: messaging-health-monitor
    applicationName: messaging-health-monitor
    gitRepo:
      repoName: messaging-health-monitor-config
      ref:
        branch: namer-stg
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp  
    helmRelease:
      valuesFiles:
        - helm/messaging-health-monitor/values.yaml
        - helm/messaging-health-monitor/overrides/namer-stg.yaml
    alert:
      channel: core-gitops
