apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gcpquotas-on-boarding
  namespace: sre-gcpquotas
spec:
  interval: 2m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: sre-gcpquotas
      interval: 1m

  values:
    namespace: sre-gcpquotas
    releaseName: gcpquotas
    applicationName: gcpquotas

    alert:
      enabled: false

    gitRepo:
      repoName: gcpquotas-config
      ref:
        branch: stg-env-config
    helmRelease:
      valuesFiles:
        - helm/gcpquotas/values.yaml
        - helm/gcpquotas/overrides/gcpquotas-stg.yaml
