apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core-emea-prd
  - journaling-emea-prd
  - notifications-emea-prd
  - prd-apims
  - users-emea-prd
  - messaging-health-monitor-emea-prd
  - applications-emea-prd
  - flagger