apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: journaling-on-boarding
  namespace: journaling-namer-sandbox
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: journaling-namer-sandbox
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: journaling-namer-sandbox
    releaseName: journaling
    applicationName: nep-journaling
    gitRepo:
      repoName: nep-journaling-config
      ref:
        branch: namer-sandbox
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp  
    helmRelease:
      timeout: 55m # Needed to give other jobs time to finish.
      valuesFiles:
        - helm/nep-journaling/values.yaml
        - helm/nep-journaling/overrides/namer-sandbox.yaml
    alert:
      channel: core-gitops
