apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: image-on-boarding
  namespace: items
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: items
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: items
    releaseName: image-apac-prd
    applicationName: image
    gitRepo:
      repoName: image-config
      ref:
        branch: apac-prd-env-config
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/image/values.yaml
        - helm/image/overrides/apac-prd.yaml
    alert:
      channel: bsp-apac-prd-flux-applications
