apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-notifier-nonprod
resources:
- namespace.yaml
- ../../../../../common-resources/default/github
- ../../../../../common-resources/default/certs/ncrcloud
- github-notifier.yaml
