---
apiVersion: v1
kind: Namespace
metadata:
  name: argus
  labels:
    istio.io/rev: asm-managed-stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argus-on-boarding
  namespace: argus
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: argus
      interval: 5m
  values:
    namespace: argus
    applicationName: argus
    gitRepo:
      repoName: argus-config
      ref:
        branch: dev
    helmRelease:
      valuesFiles:
        - helm/argus/values.yaml
        - helm/argus/overrides/dev.yaml
    alert:
      channel: 
      - alert-test