apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: users-on-boarding
  namespace: users-namer-dev
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: users-namer-dev
      interval: 5m
## Values overridden for this deployment
  values:
    namespace: users-namer-dev
    releaseName: users
    applicationName: users
    gitRepo:
      repoName: core-config
      ref:
        branch: users-namer-dev
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp  
    helmRelease:
      valuesFiles:
        - helm/users/values.yaml
        - helm/users/overrides/namer-dev.yaml
    alert:
      channel: core-gitops
