apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: order-expiration-processor-on-boarding
  namespace: ordering
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: ordering
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: ordering
    releaseName: order-expiration-processor-emea-prd
    applicationName: order-expiration-processor
    gitRepo:
      repoName: order-expiration-processor-config
      ref:
        branch: emea-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/order-expiration-processor/values.yaml
        - helm/order-expiration-processor/overrides/emea-prd.yaml
    alert:
      channel:
        - bsp-emea-prd-flux-applications
        - hoth-flux-prd-emea
