apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: test-asm-5.0.7-test-on-boarding
  namespace: messaging
spec:
  interval: 5m
  chart:
    spec:
      # Chart: https://github.com/ncr-bsp/bsp-sre-gitops/tree/on-board-helm-submodules/helm/bsp-messaging
      chart: ./helm/bsp-messaging
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm-submodules
        namespace: messaging
      interval: 1m
  values:
    releaseNamePostfix: test-asm507
    gitRepo:
      repoName: messaging-core-test-config
      helmBaseDirectory: messaging/build/core/helm
      ref:
        branch: namer-dev-5.0.7
      secretRef:
        name: ghe-repository-auth
    region: us
    environment: dev
    coreAppName: test-asm
    helmRelease:
      valuesFiles:
        - messaging/build/core/helm/messaging-gcp/values.yaml
        - messaging/build/core/helm/messaging-gcp/overrides/us-dev.yaml
        - helm/overrides/business-services-platform-dev.yaml
    alert:
      channel: core-gitops
