apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core-napac-prd
  - journaling-napac-prd
  - notifications-napac-prd
  - prd-apims
  - users-napac-prd
  - messaging-health-monitor-napac-prd
  - applications-napac-prd
  - flagger