apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: site-on-boarding
  namespace: ordering
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: ordering
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: ordering
    releaseName: site-emea-prd
    applicationName: site
    gitRepo:
      repoName: site-config
      ref:
        branch: emea-prd-env-config
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/site/values.yaml
        - helm/site/overrides/emea-prd.yaml
    alert:
      channel: bsp-emea-prd-flux-applications
