apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-analytics-onboarding
  namespace: dev-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: dev-apims
      interval: 5m
  values:
    namespace: dev-apims
    releaseName: analytics
    applicationName: analytics
    gitRepo:
      repoName: apims-analytics-config
      ref:
        branch: namer-dev
    helmRelease:
      valuesFiles:
        - helm/analytics/values.yaml
        - helm/analytics/overrides/asm/namer-dev.yaml
    alert:
      channel: apims-analytics-gitops