apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications-namer-stg
resources:
- ../../../../../common-resources/default/certs/ncrcloud
- ../../../../../common-resources/default/github
- ../../../../../common-resources/default/slack
- namespace.yaml
- applications.yaml
