apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: api-launch-onboarding
  namespace: dev-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: dev-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: dev-apims
    releaseName: api-launch-service-v5mc00e
    applicationName: api-launch
    gitRepo:
      repoName: api-launch-function-config
      ref:
        branch: namer-dev
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      timeout: 60m # Needed to give cloud functions time to deploy
      valuesFiles:
        - helm/api-launch/values.yaml
        - helm/api-launch/overrides/namer-dev.yaml
    alert:
      channel: api-launch-gitops
