apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: applications-on-boarding
  namespace: applications-namer-prd
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: applications-namer-prd
      interval: 5m
## Values overridden for this deployment
  values:
    namespace: applications-namer-prd
    releaseName: applications
    applicationName: applications
    gitRepo:
      repoName: core-config
      ref:
        branch: applications-namer-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp  
    helmRelease:
      valuesFiles:
        - helm/applications/values.yaml
        - helm/applications/overrides/namer-prd.yaml
    alert:
      channel: core-gitops
