---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pe-ncrvoyix-site-on-boarding
  namespace: pe-ncrvoyix-site
spec:
  interval: 10m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: pe-ncrvoyix-site
      interval: 10m

  values:
    namespace: pe-ncrvoyix-site
    releaseName: pe-ncrvoyix-site-stg
    applicationName: pe-ncrvoyix-site
    gitRepo:
      repoName: pe-ncrvoyix-site-config
      orgName: ncr-swt-sre
      ref:
        branch: stg
    alert:
      enabled: false
    helmRelease:
      valuesFiles:
        - helm/pe-ncrvoyix-site/values.yaml
        - helm/pe-ncrvoyix-site/overrides/pe-ncrvoyix-site-stg.yaml
