apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pe-ncrvoyix-site
resources:
- ../../../../common-resources/default/github
- ../../../../common-resources/default/slack
- ../../../../common-resources/default/certs/ncrcloud
- namespace.yaml
- helm-release.yaml
