apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bsp-security-proxy-onboarding
  namespace: prd-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: prd-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: prd-apims
    releaseName: bsp-security-proxy-nc1jkfp
    applicationName: bsp-security-proxy
    gitRepo:
      repoName: bsp-security-proxy-config
      ref:
        branch: namer-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/bsp-security-proxy/values.yaml
        - helm/bsp-security-proxy/overrides/namer/namer-prd-override.yaml
    alert:
      channel: shared-flow-gitops
