apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: order-monitor-on-boarding
  namespace: ordering
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: ordering
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: ordering
    releaseName: order-monitor-app-apac-prd
    applicationName: order-monitor
    gitRepo:
      repoName: order-monitor-config
      ref:
        branch: apac-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/order-monitor/values.yaml
        - helm/order-monitor/overrides/apac-prd.yaml
    alert:
      channel:
        - bsp-apac-prd-flux-applications
        - hoth-flux-prd-apac
