apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: bsp-sre-gitops
spec:
  interval: 1m
  url: https://github.com/ncrvoyix-bsp/bsp-sre-gitops
  secretRef:
    name: ghe-repository-auth
  ref:
    branch: master
