apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- applications-namer-stg
- users-namer-stg
- messaging-health-monitor-namer-stg
- journaling-namer-stg
- core-namer-stg
- stg-apims
- notifications-namer-stg
- site-security-namer-stg
- ncr-id
- gateway.yaml
- flagger
