apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-entitlements-onboarding
  namespace: stg-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: stg-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: stg-apims
    releaseName: entitlements
    applicationName: apip-entitlements
    gitRepo:
      repoName: apip-entitlements-config
      ref:
        branch: namer-stg-transition
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/apip-entitlements/values.yaml
        - helm/apip-entitlements/overrides/namer/namer-stg-override.yaml
    alert:
      channel: apims-entitlements-gitops