apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: catalog-batch-on-boarding
  namespace: items
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: items
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: items
    releaseName: catalog-batch-prd-napac
    applicationName: catalog-batch
    gitRepo:
      repoName: catalog-batch-config
      ref:
        branch: napac-prd-env-config
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/catalog-batch/values.yaml
        - helm/catalog-batch/overrides/apigee-napac-prd.yaml
    alert:
      channel: bsp-napac-prd-flux-applications
