apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: menu-maker-on-boarding
  namespace: items
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: items
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: items
    releaseName: menu-maker-napac-prd
    applicationName: menu-maker
    gitRepo:
      repoName: menu-config
      ref:
        branch: napac-prd-env-config
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/menu-maker/values.yaml
        - helm/menu-maker/overrides/napac-prd.yaml
    alert:
      channel: bsp-napac-prd-flux-applications
