apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: flagger-repository
  namespace: istio-system
spec:
  interval: 10m0s
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 10m0s
  chart:
    spec:
      version: v1.36.1
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger-repository
        namespace: istio-system
      interval: 10m0s
  values:
    meshProvider: kubernetes
    slack.channel: bsp-dev-flux-system
    slack.user: flagger
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-helmtester
  namespace: kube-system
spec:
  interval: 10m0s
  chart:
    spec:
      version: v0.31.0
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: flagger-repository
        namespace: istio-system
      interval: 10m0s