apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-auditing-onboarding
  namespace: dev-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: dev-apims
      interval: 5m
  ## Values overridden for this deployment
  values:
    namespace: dev-apims
    releaseName: auditing-dev-ts-cdt6c24
    applicationName: auditing
    gitRepo:
      repoName: apims-auditing-config
      ref:
        branch: namer-dev
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/auditing/values.yaml
        - helm/auditing/overrides/namer-dev.yaml
    alert:
      channel: apims-auditing-gitops
