apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: items-ingest
resources:
- ../../../../../common-resources/default/certs/ncrcloud
- ../../../../../common-resources/default/github
- ../../../../../common-resources/default/slack
- ../../../../../common-resources/gke-management/backend-config
- ../../../../../common-resources/gke-management/frontend-config
- namespace.yaml
- items-ingest.yaml
- items-ingest-user.yaml
