apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sre-ncrbot
resources:
- ../../../../common-resources/default/github
- ../../../../common-resources/default/certs/ncrcloud
- sre-ncrbot.yaml
