apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sre-ncrbot-on-boarding
  namespace: sre-ncrbot
spec:
  interval: 2m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: sre-ncrbot
      interval: 1m

  values:
    namespace: sre-ncrbot
    releaseName: sre-ncrbot
    applicationName: ncrbot-app

    alert:
      enabled: false

    gitRepo:
      repoName: sre-ncrbot-config
      ref:
        branch: stg-env-config
    helmRelease:
      valuesFiles:
        - helm/ncrbot-app/values.yaml
        - helm/ncrbot-app/overrides/srebot-stg.yaml

