apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ncr-id
resources:
  - ../../../../../common-resources/default/certs/ncrcloud
  - ../../../../../common-resources/default/github
  - ../../../../../common-resources/default/slack
  - ncr-id.yaml
  - namespace.yaml