apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-teams-onboarding
  namespace: dev-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: on-board-helm
        namespace: dev-apims
      interval: 5m
  # Values overridden for this deployment
  values:
    namespace: dev-apims
    releaseName: teams
    applicationName: apims-teams
    gitRepo:
      repoName: apims-teams-config
      ref:
        branch: namer-rc-dev
    helmRelease:
      valuesFiles:
        - helm/apims-teams/values.yaml
        - helm/apims-teams/overrides/asm/rc/rc-dev-override.yaml
    alert:
      channel: apims-teams-gitops
