apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apims-export-data-onboarding
  namespace: prd-apims
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/bsp-applications
      sourceRef:
        kind: GitRepository
        name: ghe-on-board-helm
        namespace: prd-apims
      interval: 5m
  values:
    namespace: prd-apims
    releaseName: auditing-data-export-yb2qho5
    applicationName: export-data
    gitRepo:
      repoName: apims-data-exporter-config
      ref:
        branch: apac-prd
      secretRef:
        name: ghe-repository-auth
      orgName: ncrvoyix-bsp
    helmRelease:
      valuesFiles:
        - helm/export-data/values.yaml
        - helm/export-data/overrides/apac-prod.yaml
    alert:
      channel: apims-data-exporter-gitops
